version: "3.9"
services:
  microservice:
    build:
      context: .
      args:
        - JAR_FILE=target/*.jar
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL="ThisIsAProductionSecret"